### ISSUE TITLE
Strona /partners jako node type + views

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/website_2015#12]

**Comment by dinerrr** [comment]
kroki:
1) dodaję noda media partner
2) oczekuję, że w zakładce menu głównego zobaczę dodanego noda, lecz tak nie jest
3) zaglądam do views i widze ze adres wiews z partnerami to /partners-page a do menu głównego podpięte jest /partners
4) po przejściu na /partners-page widzę noda, którego dodałem.
