### ISSUE TITLE
Featured speakers - blok na stronie głównej

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/website_2015#19]
- najlepiej dodać nową rolę dla takich użytkowników i w widoku wyświetlać userów tylko o takiej roli

**Comment by MaciejLukianski** [comment]
Zrobione polem na user.

**Comment by dinerrr** [comment]
przenieść ten blok pod sponsorów na stronę główną i niech się wyświetlają w poziomie
