### ISSUE TITLE
Język PL

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/website_2015#2]

**Comment by grzegorzbartman** [comment]
Biorę na siebię. Zrobię z entity translations https://www.drupal.org/project/entity_translation

**Comment by MaciejLukianski** [comment]
Entity translation włączone razem z modułem title. Wszystkie rodzaje zawartości ustawione jako "Enabled with field translation"

Kolejny krok to ustawić per pole czy jest tłumaczone czy nie.

**Comment by MaciejLukianski** [comment]
Pola ustawione jako do tłumaczenia. Teraz trzeba testować żeby wykryć co jeszcze do zmiany.

**Comment by MaciejLukianski** [comment]
To raczej na koniec do testowania, jak będą treści wchodziły

**Comment by grzegorzbartman** [comment]
Dla sesji ja bym wyłączył wersje językowe. Teraz są 2 selecty przy dodawaniu noda: Language i "Session language". To moze byc troche mylące. No i chyba bedzie prosciej jak bedzie jeden jezyk dla sesji

**Comment by grzegorzbartman** [comment]
robie zmiany w branchu feature/issue_2_lang_pl

**Comment by grzegorzbartman** [comment]
Nody news i page mają możliwość tłumaczenia.
Reszte nodów mozna zostawić.

TODO:
Translate menu links
