### ISSUE TITLE
Zarejestruj się -> "się" ->  w wersji mobilnej nie miesci sie w linii

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/website_2015#33]
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/205021/1449108/1pUsvckJ7Mqd0Rs/Screenshot_2015-03-09-10-17-53.png

**Comment by car3oon** [comment]
@grzegorzbartman przy jakiej rozdzieczości to występuje?

**Comment by wodzik** [comment]
1080x1920 tak jak rozdzielczość obrazka.

**Comment by grzegorzbartman** [comment]
ale to rozdzielczość ekranu telefonu, przeglądarka wyświetla to zazwyczaj jako 360, 420 czy 480px, zaleznie od typu telefonu

**Comment by wodzik** [comment]
Jak to sprawdzić na telefonie?

**Comment by grzegorzbartman** [comment]
Wejdz na http://www.whatismyscreenresolution.com/ w telefonie

u mnie np pokazuje 360x640 na Chrome a ekran w telefonie tez mam full hd

2015-03-16 9:41 GMT+01:00 wodzik notifications@github.com:

> Jak to sprawdzić na telefonie?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DrupalCampWroclaw/website_2015/issues/33#issuecomment-81506078
> .

## 

Regards
Grzegorz Bartman
mobile: +48 882 515 514
e-mail: grzegorz.bartman@droptica.com
skype: grzegorzbartman

DROPTICA Sp. z o.o.
Ostrowskiego 30/36, 53-238 Wrocław, Poland
Wassowskiego 12, 80-225 Gdańsk, Poland
www.droptica.com
info@droptica.com

**Comment by wodzik** [comment]
dokładnie tak samo u mnie.
