### ISSUE TITLE
checkbox czy bede na konferencji

### ISSUE THREAD

**Issue by grzegorzbartman** [DrupalCampWroclaw/website_2015#8]
- aktualnie niedostępne pole dla wszystkich (field permissions module)
- włączymy je na 1-2 tygodnie przed konferencją

**Comment by MaciejLukianski** [comment]
Dodałem pole pozwalające zaznaczyć czy się będzie czy nie i w które dni. Można ewentualnie walidację dodać żeby się nie dało wybrać nieobecności i dni.

**Comment by dinerrr** [comment]
trzeba dodać walidację, gdy jest zaznaczone nie bede na konferencji to niech inne checkboxy-y niech będą odznaczone.
Teraz nie ma sensu ta fuknkcjonalność (nie jest użytkowniko odporna).
